name: wound_recognition_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  go_router: ^13.1.0
  http: 1.3.0
  intl: ^0.17.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_native_splash: ^2.3.5
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "0xFFA5D6A7" # achtergrondkleur
  image: assets/WondherkenningsPoster.png # je logo
  android: true
  ios: true
